# Generated by Django 4.1.7 on 2023-02-19 08:26

import cars.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='car',
            name='model',
        ),
        migrations.AddField(
            model_name='car',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to=cars.models.upload_to),
        ),
        migrations.AddField(
            model_name='car',
            name='url',
            field=models.URLField(blank=True, default=None, null=True),
        ),
    ]
